### ISSUE TITLE
$numberLong imported as object to ES 5

### ISSUE THREAD

**Issue by webfrank** [ozlerhakan/mongolastic#24]
Hi,
  I have a mongo collection with several fields like {"$numberLong":"1502353998000"} and them are imported to ES the same and not as 1502353998000

**Comment by winder** [comment]
Try setting long to string to true in your yaml config

**Comment by webfrank** [comment]
Yes but I got it mapped to text instead of long and I cannot do operation on that field.

**Comment by winder** [comment]
Mongo has a "codec" plugin system, since there are already a couple being
configured by mongolastic you could add another flag pretty easily (or
modify `CustomLongCodec` in your local branch). Here is the relevant code
<https://github.com/ozlerhakan/mongolastic/search?utf8=%E2%9C%93&q=CustomLongCodec&type=>
.

You might also be able to define the schema in elasticsearch.
